spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nimatest?createDatabaseIfNotExist=true
    username: nimauser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
server:
  port: 7070
